name: Deploy

on:
  pull_request:
    # types: [ synchronize, reopend, opned, closed]
    branches:
      - main
  pr: 
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: lint-check
        run: |
          echo "lint check..." 

  deploy-alpha:
    name: Deploy Alpha
    runs-on: ubuntu-latest
    environment: development
    #if: github.event.pull_request.merged && github.event.action == 'closed'
    if: github.event_name == 'push' && github.event.pr.conclusion != 'success'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          echo "run development build"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          echo "run production build"