name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: lint-check
        run: |
          echo "lint check..." 

  deploy-alpha:
    name: Deploy Alpha
    needs: pr
    runs-on: ubuntu-latest
    environment: development
    if: github.event.pull_request.merged && github.event.action == 'closed'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          echo "run development build"

  deploy:
    name: Deploy
    needs: deploy-alpha
    runs-on: ubuntu-latest
    environment: development
    if: github.event.workflow_dispatch
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          echo "run production build"